# Generated by Django 4.1.2 on 2022-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default='maria', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
